### ISSUE TITLE
Blocking on knowing how to use github issues effectively for small non-milestone tasks

### ISSUE THREAD

**Issue by jonleung** [hackclub/discussions#6]
@zachlatta @MaxWofford , so if post something on github issues, what are your thoughts on having the assignee / tagged people respond with the fact that they saw it and when they think they may be able to do it by (a valid answer is never) by the end of each day? 

In Asana, I would be able to see the open tasks in one central place and poke the person easily. This is less of the case now. I could however duplicate the task into my task management system but that seems redundant? Thoughts?

**Comment by zachlatta** [comment]
Mmm, I'm not sure what my thoughts are on setting the precedent of deadlines. What if we just create issues, tag the relevant people, and wait for them to do it? If the lack of deadlines turns out to become a blocking issue, we can figure out a solution later.

**Comment by jonleung** [comment]
@zachlatta @MaxWofford

I can't figure out how to put some todos into Github Issues in a way that makes sense: see https://github.com/hackedu/mgmt/issues
(1) some of this probably shouldn't be public
(2) there are too many scattered todos

This is *immensely* stressing me out right now:
Also, this list doesn't make any sense not in a task management system https://docs.google.com/spreadsheets/d/1JhoBvFTem-R0Nv-yt7FIJUvu28yq78oodyLD-KXFFJM/edit#gid=1510877698. Putting this Asana where people can go through stages makes WAY more sense.

Also, having many different solutions is also stressing me out
1) Your own task management solution
2) Pipedrive
3) Gthub Issues
4) Random Spreadsheets

Having all these right now is really overwhelming me right now. I'd *really* prefer to consolidate to one system. One solution is to use Github to outline major goals in a sprint (basically, a synthesis of meeting notes for what we decide are our most major tasks) that would be duplicated into the Asana (pasted in). As people work towards each part of the sprint, they will check them off in the github. While this was happening, the more intimate details of the thing would be in Asana because I don't know how to organize this on Github.

**Comment by zachlatta** [comment]
Is this resolved after our discussion last night?

--
Zach Latta
Executive Director of hackEDU[https://hackedu.us/]
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta


On Thu, Apr 9, 2015, at 07:26 PM, Jonathan Leung wrote:
> @zachlatta[https://github.com/zachlatta] @MaxWofford[https://github.com/MaxWofford]


> I can't figure out how to put some todos into Github Issues in a way that makes sense: see https://github.com/hackedu/mgmt/issues
> 
(1) some of this probably shouldn't be public
> 
(2) there are too many scattered todos

> This is *immensely* stressing me out right now:
> 
Also, this list doesn't make any sense not in a task management system
https://docs.google.com/spreadsheets/d/1JhoBvFTem-R0Nv-yt7FIJUvu28yq78oodyLD-KXFFJM/edit#gid=1510877698.
Putting this Asana where people can go through stages makes WAY more
sense.

> Also, having many different solutions is also stressing me out
> 
1) Your own task management solution
> 
2) Pipedrive
> 
3) Gthub Issues
> 
4) Random Spreadsheets

**Comment by jonleung** [comment]
Let's review after
- [ ] putting together the document on processes
- [ ] setting a date and time to evaluate each sprint, perhaps on Fridays?


—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083

**Comment by zachlatta** [comment]
> - [ ] setting a date and time to evaluate each sprint, perhaps on
>   Fridays?

What about on Monday during our sprint discuss?

>- [ ] putting together the document on processes

@JacobEdelman expressed interest in taking lead on this. Perhaps we
should do our current system for a week, figure out what works and what
doesn't, and then put together a first draft of that document? We'll
have concrete examples and experience to refer to then.

**Comment by JacobEdelman** [comment]
I've written a document for HackEDU club organizer to introduce them to Github for networking. It turned out not to be too much on helping us organize how we use Github for running HackEDU. Waiting a week to figure out what works definitely seems like a good idea for me, though during that week we should definitely be willing to try different things to see what happens.

**Comment by zachlatta** [comment]
One of the pieces of advice I just got from the meeting I was in was that documents outlining processes often have issues and generally aren't effective in organizations.

Perhaps we could have a bullet point list of hackEDU's GitHub/IRC workflow? Super brief and easy to modify.

**Comment by JacobEdelman** [comment]
:+1:

**Comment by zachlatta** [comment]
I assume if hackedu/docs#27 goes through, this list of processes should go in `hackedu/hackedu`? Or perhaps `hackedu/meta`?

**Comment by JacobEdelman** [comment]
I'd go with `hackedu/meta`. The only things on `hackedu/hackedu` should be things relating directly to contributors. (eh, club leaders still feels more natural to say)

**Comment by zachlatta** [comment]
Yeah, `hackedu/meta` sounds good.

**Comment by zachlatta** [comment]
Closing due to repo deprecation.
