### ISSUE TITLE
Should Jonathan be always on call?

### ISSUE THREAD

**Issue by jonleung** [hackclub/discussions#7]

**Comment by zachlatta** [comment]
So, to clarify, this discussion is about whether @jonleung should be expected to be "on call" the majority of the time to respond to IRC pings and anything hackEDU related.

Want to close this discussion for now and reopen this issue down the line if we decide we need to talk about this? I don't think this is super blocking yet and we have more important things we can spend our time on.

**Comment by jonleung** [comment]
Just to jot my thoughts down:

I believe that for things that are time sensitive, I think it is important for me to be able to be reached immediately.The communication method should trigger me immedately so I can address it asap.

However, for things that are not time sensitive and I can resolve them later, I think it is important that I don't treat these things as if they are urgent.

If there is no distinction between the two, it will be very hard for me to focus on my current tasks because I will be pulled out of my flow for things  that are not time sensitive when I could have just resolved it at a later time with no consequences.

So the reason I don't want to commit to always be reachable on the #hackedu channel when I get a ping because there are many times that I am pinged where the message is certainly important, but not that time sensitive (i.e. can be resolved in an hour or two or by end of day or sometimes even later).

Because the current convention in the way we use IRC does not seem to distinguish no discrepancy between urgent and not urgent messages, I do not want to commit to always being reachable immediately through the current way we use this medium.

I am happy to:
(1) Find a way to use IRC to make this distinction (If I receive an ping and the hashtag #important, then IFTTT gives me a phone call)
(2) Using some other communication medium (such as a phone call) to get my attention.

Aside: @zachlatta, thanks for getting me to practice articulating my thoughts over text, I believe that I am improving.

**Comment by zachlatta** [comment]
Perhaps this is simply a case of premature optimization and we should leave things as is for now? In the case that you're pinged for something time sensitive and don't respond, we can just scramble and find another way to get to you.

I question the value of putting another process in place this early into experimenting with IRC/GitHub.

**Comment by zachlatta** [comment]
Closing due to repo being deprecated.
